### ISSUE TITLE
Is the "Enforce case-sensitive file path checks" option only for Windows? 

### ISSUE THREAD

**Issue by sparkhi** [digital-preservation/csv-validator#462]
"Enforce case sensitive file path check" - how does it work, is it only for Windows?
If left as unchecked, does it check paths ignoring case? 
how does that work on linux where the file system itself is case sensitive?

**Comment by DavidUnderdown** [comment]
Primarily for Windows, yes. Use case, digital archivists tend to run CSV Validator on the material on the transfer hard drive right after receipt from the transferring body. This is done on one of the Windows machines in the lab. Once we actually get to ingest, the CSV Validation tests are done in pre-ingest and ingest, both run in *nix environments. There were occasions where the check on Windows passed, everything seemed OK, so we proceeded to ingest only for CSV Validation to fail in pre-ingest due to a case mismatch. So selecting the check box enforces a case sensitive check in an environment where case sensitivity isn't usually an issue. On a *nix machine it doesn't actually make any difference, the operating system would report a failure anyway in the event of a case mismatch in a fileExists or checksum test.

**Comment by sparkhi** [comment]
Thanks @DavidUnderdown 
I wonder if there are users who want that option of case-insensitive comparison, otherwise we could simply force it to be case sensitive all the time and do away with the option from the UI / CLI

**Comment by DavidUnderdown** [comment]
If you're only operating on Windows, always enforcing case sensitivity is likely to cause more issues/confusion. Also the problems usually arise when the CSV file is manually edited at some point in the process, so if you're not doing that the chances are the default will be fine as well.

**Comment by sparkhi** [comment]
As per discussion, this is non-issue. Closing it.
