### ISSUE TITLE
Which csv schema language version is implemented by the new release candidate?

### ISSUE THREAD

**Issue by DavidUnderdown** [digital-preservation/csv-validator#465]
Hi

Previously we had the 1.1 series which supported only changes to CSV Schema Language 1.1, and the 1.2 series which additionally included the draft updates to schema language 1.2. Naming the new release 1.3 breaks the link between the naming of the CSV validator release and the schema language supported so could lead to confusion

**Comment by sparkhi** [comment]
There is no upgrade to schema language in this release. As there is a major change in the way the software is distributed, it was decided to go to the next minor version rather than just a patch. In addition, this version starts using semver. I think, if we actively update the software, it will have more smaller releases than the schema language, which will result in different version numbers.

**Comment by DavidUnderdown** [comment]
Yes, but does 1.3 include validating the current CSV Schema Language 1.2 draft elements? It would be helpful to note that in the release notes at least

**Comment by sparkhi** [comment]
There is no specific change for schema since 1.2-RC4. 
Looking at the release notes of 1.2-RC4 (and 1.2-RC3), I do not see any specific mention of supporting 1.2 schema. With the current release, that position will stay as it is. 
Also, I gather the latest release of the schema is still 1.1 (https://github.com/digital-preservation/csv-schema/releases) 

Having said that, I can see in the codebase that some partial work for supporting 1.2 was done at some point  but I don't believe it is complete (_which means if I use a csvs with `version 1.2` it will not flag it up as unsupported - which is probably not the right behaviour_) , so as of now, this will still only support 1.1

**Comment by steve-daly** [comment]
The schemas that we create with/for government departments have `version 1.2` in the csvs file. This is possibly in the mistaken assumption that it matches the application version (1.2-RC2) rather than the schema language, but it is what is commonly used with transfer CSVs and 1.2-RC2.  I believe that nothing would change in this behaviour with v1.3, and that we'd still say `version 1.2` in the csvs.
